CREATE OR REPLACE function upser()
returns void as $$
BEGIN
  IF EXISTS (SELECT count(*) > 0) THEN
    return;
  ELSE
   INSERT INTO countries (name, code)
   VALUES
    ('Switzerland', 'CH'),
    ('Norway', 'NO'),
    ('Croatia', 'HR'),
    ('Afghanistan', 'AF'),
    ('Aland Islands', 'AX'),
    ('Albania', 'AL'),
    ('Algeria', 'DZ'),
    ('American Samoa', 'AS'),
    ('Andorra', 'AD'),
    ('Angola', 'AO'),
    ('Anguilla', 'AI'),
    ('Antarctica', 'AQ'),
    ('Antigua and Barbuda', 'AG'),
    ('Argentina', 'AR'),
    ('Armenia', 'AM'),
    ('Aruba', 'AW'),
    ('Australia', 'AU'),
    ('Serbia', 'RS'),
    ('Azerbaijan', 'AZ'),
    ('The Bahamas', 'BS'),
    ('Bahrain', 'BH'),
    ('Bangladesh', 'BD'),
    ('Barbados', 'BB'),
    ('Belarus', 'BY'),
    ('Seychelles', 'SC'),
    ('Belize', 'BZ'),
    ('Benin', 'BJ'),
    ('Bermuda', 'BM'),
    ('Bhutan', 'BT'),
    ('Bolivia', 'BO'),
    ('Bosnia and Herzegovina', 'BA'),
    ('Botswana', 'BW'),
    ('Bouvet Island', 'BV'),
    ('Brazil', 'BR'),
    ('British Indian Ocean Territory', 'IO'),
    ('Brunei', 'BN'),
    ('Sierra Leone', 'SL'),
    ('Burkina Faso', 'BF'),
    ('Burundi', 'BI'),
    ('Cambodia', 'KH'),
    ('Cameroon', 'CM'),
    ('Canada', 'CA'),
    ('Cape Verde', 'CV'),
    ('Cayman Islands', 'KY'),
    ('Central African Republic', 'CF'),
    ('Chad', 'TD'),
    ('Chile', 'CL'),
    ('People`s Republic of China', 'CN'),
    ('Christmas Island', 'CX'),
    ('Cocos (Keeling) Islands', 'CC'),
    ('Colombia', 'CO'),
    ('Comoros', 'KM'),
    ('Republic of the Congo', 'CG'),
    ('Democratic Republic of the Congo', 'CD'),
    ('Cook Islands', 'CK'),
    ('Costa Rica', 'CR'),
    ('Kosovo', 'XK'),
    ('Cuba', 'CU'),
    ('Singapore', 'SG'),
    ('Solomon Islands', 'SB'),
    ('Somalia', 'SO'),
    ('Djibouti', 'DJ'),
    ('Dominica', 'DM'),
    ('Dominican Republic', 'DO'),
    ('Ecuador', 'EC'),
    ('Egypt', 'EG'),
    ('El Salvador', 'SV'),
    ('Equatorial Guinea', 'GQ'),
    ('Eritrea', 'ER'),
    ('South Africa', 'ZA'),
    ('Ethiopia', 'ET'),
    ('Falkland Islands', 'FK'),
    ('Faroe Islands', 'FO'),
    ('Fiji', 'FJ'),
    ('South Georgia and the South Sandwich Islands', 'GS'),
    ('Sri Lanka', 'LK'),
    ('French Guiana', 'GF'),
    ('French Polynesia', 'PF'),
    ('French Southern and Antarctic Lands', 'TF'),
    ('Gabon', 'GA'),
    ('The Gambia', 'GM'),
    ('Georgia (country)', 'GE'),
    ('Togo', 'TG'),
    ('Ghana', 'GH'),
    ('Gibraltar', 'GI'),
    ('Greenland', 'GL'),
    ('Grenada', 'GD'),
    ('Guadeloupe', 'GP'),
    ('Guam', 'GU'),
    ('Guatemala', 'GT'),
    ('Guernsey', 'GG'),
    ('Guinea', 'GN'),
    ('Guinea-Bissau', 'GW'),
    ('Guyana', 'GY'),
    ('Haiti', 'HT'),
    ('Heard Island and McDonald Islands', 'HM'),
    ('Vatican City', 'VA'),
    ('Honduras', 'HN'),
    ('Hong Kong', 'HK'),
    ('Sudan', 'SD'),
    ('Iceland', 'IS'),
    ('India', 'IN'),
    ('Indonesia', 'ID'),
    ('Iran', 'IR'),
    ('Iraq', 'IQ'),
    ('Suriname', 'SR'),
    ('Isle of Man', 'IM'),
    ('Israel', 'IL'),
    ('Svalbard and Jan Mayen', 'SJ'),
    ('Jamaica', 'JM'),
    ('Japan', 'JP'),
    ('Jersey', 'JE'),
    ('Jordan', 'JO'),
    ('Kazakhstan', 'KZ'),
    ('Kenya', 'KE'),
    ('Kiribati', 'KI'),
    ('North Korea', 'KP'),
    ('South Korea', 'KR'),
    ('Kuwait', 'KW'),
    ('Kyrgyzstan', 'KG'),
    ('Laos', 'LA'),
    ('Swaziland', 'SZ'),
    ('Lebanon', 'LB'),
    ('Lesotho', 'LS'),
    ('Liberia', 'LR'),
    ('Libya', 'LY'),
    ('Liechtenstein', 'LI'),
    ('Syria', 'SY'),
    ('Macau', 'MO'),
    ('Republic of Macedonia', 'MK'),
    ('Madagascar', 'MG'),
    ('Malawi', 'MW'),
    ('Malaysia', 'MY'),
    ('Maldives', 'MV'),
    ('Mali', 'ML'),
    ('Taiwan', 'TW'),
    ('Marshall Islands', 'MH'),
    ('Martinique', 'MQ'),
    ('Mauritania', 'MR'),
    ('Mauritius', 'MU'),
    ('Mayotte', 'YT'),
    ('Mexico', 'MX'),
    ('Federated States of Micronesia', 'FM'),
    ('Moldova', 'MD'),
    ('Monaco', 'MC'),
    ('Mongolia', 'MN'),
    ('Montenegro', 'ME'),
    ('Montserrat', 'MS'),
    ('Morocco', 'MA'),
    ('Mozambique', 'MZ'),
    ('Myanmar', 'MM'),
    ('Namibia', 'NA'),
    ('Nauru', 'NR'),
    ('Nepal', 'NP'),
    ('Tajikistan', 'TJ'),
    ('Netherlands Antilles', 'AN'),
    ('New Caledonia', 'NC'),
    ('New Zealand', 'NZ'),
    ('Nicaragua', 'NI'),
    ('Niger', 'NE'),
    ('Nigeria', 'NG'),
    ('Niue', 'NU'),
    ('Norfolk Island', 'NF'),
    ('Northern Mariana Islands', 'MP'),
    ('Oman', 'OM'),
    ('Pakistan', 'PK'),
    ('Palau', 'PW'),
    ('Palestinian territories', 'PS'),
    ('Panama', 'PA'),
    ('Papua New Guinea', 'PG'),
    ('Paraguay', 'PY'),
    ('Peru', 'PE'),
    ('Philippines', 'PH'),
    ('Pitcairn Islands', 'PN'),
    ('Tanzania', 'TZ'),
    ('Thailand', 'TH'),
    ('Puerto Rico', 'PR'),
    ('Qatar', 'QA'),
    ('Cote d`Ivoire', 'CI'),
    ('East Timor', 'TL'),
    ('Russia', 'RU'),
    ('Rwanda', 'RW'),
    ('Saint Barthlemy', 'BL'),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
    ('Saint Kitts and Nevis', 'KN'),
    ('Saint Lucia', 'LC'),
    ('Collectivity of Saint Martin', 'MF'),
    ('Saint Pierre and Miquelon', 'PM'),
    ('Saint Vincent and the Grenadines', 'VC'),
    ('Samoa', 'WS'),
    ('San Marino', 'SM'),
    ('South Sudan', 'SS'),
    ('Saudi Arabia', 'SA'),
    ('Senegal', 'SN'),
    ('Saint Maarten (Dutch part)', 'SX'),
    ('Curacao', 'CW'),
    ('Bonaire', 'BQ'),
    ('Sao Tome and Principe', 'ST'),
    ('Reunion', 'RE'),
    ('Tokelau', 'TK'),
    ('Tonga', 'TO'),
    ('Trinidad and Tobago', 'TT'),
    ('Tunisia', 'TN'),
    ('Turkey', 'TR'),
    ('Turkmenistan', 'TM'),
    ('Turks and Caicos Islands', 'TC'),
    ('Tuvalu', 'TV'),
    ('Uganda', 'UG'),
    ('Ukraine', 'UA'),
    ('United Arab Emirates', 'AE'),
    ('United States', 'US'),
    ('United States Minor Outlying Islands', 'UM'),
    ('Uruguay', 'UY'),
    ('Uzbekistan', 'UZ'),
    ('Vanuatu', 'VU'),
    ('Venezuela', 'VE'),
    ('Vietnam', 'VN'),
    ('British Virgin Islands', 'VG'),
    ('United States Virgin Islands', 'VI'),
    ('Wallis and Futuna', 'WF'),
    ('Western Sahara', 'EH'),
    ('Yemen', 'YE'),
    ('Zambia', 'ZM'),
    ('Zimbabwe', 'ZW'),
    ('Austria', 'AT'),
    ('Belgium', 'BE'),
    ('Bulgaria', 'BG'),
    ('Cyprus', 'CY'),
    ('Czech Republic', 'CZ'),
    ('Denmark', 'DK'),
    ('Estonia', 'EE'),
    ('Finland', 'FI'),
    ('Germany', 'DE'),
    ('Greece', 'GR'),
    ('Hungary', 'HU'),
    ('Republic of Ireland', 'IE'),
    ('Italy', 'IT'),
    ('Latvia', 'LV'),
    ('Lithuania', 'LT'),
    ('Luxembourg', 'LU'),
    ('Malta', 'MT'),
    ('Netherlands', 'NL'),
    ('Poland', 'PL'),
    ('Portugal', 'PT'),
    ('Romania', 'RO'),
    ('Slovakia', 'SK'),
    ('Slovenia', 'SI'),
    ('Spain', 'ES'),
    ('Sweden', 'SE'),
    ('France', 'FR'),
    ('United Kingdom', 'GB');
  END IF;
END;
$$ language plpgsql;

SELECT upser();